/* GENERATED by _src/build.py from _src/config.py — do not edit.
 * Change a value in _src/config.py and run `python _src/build.py`.
 * Words live in js/translations.js; only values live here. */
window.GC_CONFIG = {
  "EMAIL": "GoCuatro4@gmail.com",
  "WA_NUMBER": "9647750775533",
  "PHONE_DISPLAY": "0775 077 5533",
  "TEL": "07750775533",
  "TELEGRAM": "https://t.me/+9647750775533",
  "INSTAGRAM": "https://instagram.com/gocuatro",
  "INSTAGRAM_HANDLE": "@gocuatro",
  "FACEBOOK": "https://www.facebook.com/profile.php?id=61593175900925",
  "THREADS": "https://www.threads.com/@gocuatro",
  "TIKTOK": "",
  "SITE": "https://gocuatro.com/",
  "PRICE_MENU": "105000",
  "PRICE_PORTFOLIO": "75000",
  "PRICE_BUSINESS": "225000",
  "PRICE_BUSINESS_HI": "750000",
  "PRICE_CURRENCY": "IQD",
  "PRICE_MENU_USD": "69",
  "PRICE_PORTFOLIO_USD": "49",
  "PRICE_BUSINESS_USD": "149",
  "PRICE_BUSINESS_HI_USD": "499",
  "DAYS_MIN": "2",
  "DAYS_MAX": "4"
};
